import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import '../styles/globals.css';
import { ReviewProvider } from '@/contexts/ReviewContext';
import { AuthProvider } from '@/contexts/AuthContext';
import Header from '@/components/Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col min-h-screen`}>
        <AuthProvider>
          <Header></Header>
          <ReviewProvider>
            <main className="flex flex-1 flex-col overflow-auto">
              {children}
            </main>
          </ReviewProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
